export const products = [
  {
    label: "Нихром",
    subLabel: "Проволока нихром ",
    id: "nihrom_provoloka",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "wireNihrom",
    price: "от 4000р кг",
    title: "Проволока нихром по цене от 4000р кг., купить оптом и в розницу в",
  },
  {
    label: "Нихром",
    subLabel: "Круг нихром ",
    id: "nihrom_circle",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "circleNihrom",
    price: "от 4000р кг",
    title: "Круг нихром по цене от 4000р кг., купить оптом и в розницу в",
  },
  {
    label: "Нихром",
    subLabel: "Лента нихром",
    id: "nihrom_lenta",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "lentaNihrom",
    price: "от 4000р кг",
    title: "Лента нихром по цене от 4000р кг., купить оптом и в розницу в",
  },
  {
    label: "Фехраль",
    subLabel: "Проволока фехраль",
    id: "fehral_provoloka",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "wireFehral",
    price: "от 1000р кг",
    title: "Проволока фехраль по цене от 1000р кг., купить оптом и в розницу в",
  },
  {
    label: "Пермаллой",
    subLabel: "Лист Пермаллой",
    id: "permalloy_list",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listPermalloy",
    price: "от 5300р кг",
    title: "Лист Пермаллой по цене от 5300р кг., купить оптом и в розницу в",
  },
  {
    label: "Пермаллой",
    subLabel: "Лента Пермаллой",
    id: "permalloy_lenta",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "lentaPermalloy",
    price: "от 5300р кг",
    title: "Лента Пермаллой по цене от 5300р кг., купить оптом и в розницу в",
  },
  {
    label: "Пермаллой",
    subLabel: "Круг Пермаллой",
    id: "permalloy_circle",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "circlePermalloy",
    price: "от 5300р кг",
    title: "Круг Пермаллой по цене от 5300р кг., купить оптом и в розницу в",
  },
  {
    label: "Пермаллой",
    subLabel: "Проволока Пермаллой",
    id: "permalloy_provoloka",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "provolokaPermalloy",
    price: "от 5300р кг",
    title:
      "Проволока Пермаллой по цене от 5300р кг., купить оптом и в розницу в",
  },
  {
    label: "Пермаллой",
    subLabel: "Труба Пермаллой",
    id: "permalloy_truba",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "trubaPermalloy",
    price: "от 5300р кг",
    title: "Труба Пермаллой по цене от 5300р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 06ХН28МДТ",
    id: "nershav_list_06ХН28МДТ",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 06ХН28МДТ по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 10Х11Н20Т2Р",
    id: "nershav_list_10Х11Н20Т2Р",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 10Х11Н20Т2Р по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 10Х17Н13М2Т",
    id: "nershav_list_10Х17Н13М2Т",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 10Х17Н13М2Т по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 30Х13",
    id: "nershav_list_30Х13",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 30Х13 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 40Х13",
    id: "nershav_list_40Х13",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 40Х13 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 201",
    id: "nershav_list_AISI_201",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 201 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 304",
    id: "nershav_list_AISI_304",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 304 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 310s",
    id: "nershav_list_AISI_310s",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 310s по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 316L",
    id: "nershav_list_AISI_316L",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 400р кг",
    title:
      "Лист нержавеющий AISI 316L по цене от 400р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 316Ti",
    id: "nershav_list_AISI_316Ti",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 400р кг",
    title:
      "Лист нержавеющий AISI 316Ti по цене от 400р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 321",
    id: "nershav_list_AISI_321",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 550р кг",
    title:
      "Лист нержавеющий AISI 321 по цене от 550р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист AISI 430",
    id: "nershav_list_AISI_430",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 430 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 08Х18Н10",
    id: "nershav_list_08Х18Н10",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 08Х18Н10 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 12Х18Н10Т",
    id: "nershav_list_12Х18Н10Т",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 550р кг",
    title:
      "Лист нержавеющий 12Х18Н10Т по цене от 550р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 20Х13",
    id: "nershav_list_20Х13",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 20Х13 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лист нержавеющий",
    subLabel: "Лист 20Х23Н18",
    id: "nershav_list_20Х23Н18",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "listNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий 20Х23Н18 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лента нержавеющая",
    subLabel: "Лента 12Х18Н10Т",
    id: "nershav_lenta_20Х23Н18",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "lentaNershav",
    price: "от 550р кг",
    title:
      "Лист нержавеющий 20Х23Н18 по цене от 550р кг., купить оптом и в розницу в",
  },
  {
    label: "Лента нержавеющая",
    subLabel: "Лента AISI 201",
    id: "nershav_lenta_AISI_201",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "lentaNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 201 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Лента нержавеющая",
    subLabel: "Лента AISI 304",
    id: "nershav_lenta_AISI_304",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "lentaNershav",
    price: "от 250р кг",
    title:
      "Лист нержавеющий AISI 304 по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Уголок нержавеющий",
    subLabel: "Уголок нержавеющий AISI 304 (08Х18Н10)",
    id: "nershav_corner_AISI_304",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "cornerNershav",
    price: "от 250р кг",
    title:
      "Уголок нержавеющий AISI 304 (08Х18Н10) по цене от 250р кг., купить оптом и в розницу в",
  },
  {
    label: "Трубы нержавеющие",
    subLabel: "Труба нержавеющая бесшовная",
    id: "nershav_truba_bezshov",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "trubaNershav",
    price: "от 1000р кг",
    title:
      "Труба нержавеющая бесшовная по цене от 1000р кг., купить оптом и в розницу в",
  },
    {
    label: "Трубы нержавеющие",
    subLabel: "Труба нержавеющая электросварная",
    id: "nershav_truba_electrosvar",
    amount: "",
    isInStock: "Имеется в наличии",
    img: "trubaNershav",
    price: "от 600р кг",
    title:
      "Труба нержавеющая электросварная по цене от 600р кг., купить оптом и в розницу в",
  },
];
