export const menuCatalog = [
  {
    label: "Цветные металлы",
    href: "tsvetnoi-prokat",
    metaData: "Купить Цветной металлопрокат оптом и в розницу",
    links: [
      {
        title: "Алюминий",
        link: "tsvetnoi-prokat/aluminum",
        img: "aluminumImg",
        metaData: "Алюминиевый Прокат купить",
      },
      {
        title: "Бронза",
        link: "tsvetnoi-prokat/bronze",
        img: "bronzeImg",
        metaData: "Бронзовый Прокат купить",
      },
      {
        title: "Дюраль",
        link: "tsvetnoi-prokat/dural",
        img: "duralImg",
        metaData: "Дюралевый Прокат купить",
      },
      {
        title: "Олово",
        link: "tsvetnoi-prokat/olovo",
        img: "olovoImg",
        metaData: "Оловянный Прокат купить",
      },
      {
        title: "Титан",
        link: "tsvetnoi-prokat/titan",
        img: "titanImg",
        metaData: "Титановый Прокат купить",
      },
      {
        title: "Медь",
        link: "tsvetnoi-prokat/copper",
        img: "copperImg",
        metaData: "Медный Прокат купить",
      },
      {
        title: "Латунь",
        link: "tsvetnoi-prokat/brass",
        img: "brassImg",
        metaData: "Латунный Прокат купить",
      },
      {
        title: "Свинец",
        link: "tsvetnoi-prokat/lead",
        img: "leadImg",
        metaData: "Свинцовый Прокат купить",
      },
      {
        title: "Никель",
        link: "tsvetnoi-prokat/nikel",
        img: "leadImg",
        metaData: "Никелевый Прокат купить",
      },
    ],
  },
  {
    label: "Трубопроводная арматура",
    href: "trubniy-prokat",
    metaData: "Купить Трубопроводная арматура оптом и в розницу",
    links: [
      // {
      //   title: "Запорная Арматура",
      //   link: "trubniy-prokat/zapor",
      //   img: "zaporTrubCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Отопление",
        link: "trubniy-prokat/otoplenye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Водоснабжение",
        link: "trubniy-prokat/vodosnabshenye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "ГВС",
        link: "trubniy-prokat/gvs",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Вентили нержавеющие",
        link: "trubniy-prokat/venteli-nershav",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Вентили стальные",
        link: "trubniy-prokat/venteli-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Чугунные вентили",
        link: "trubniy-prokat/venteli-shugunye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фланцевые виброкомпенсаторы",
        link: "trubniy-prokat/flancevye-vibrokompensatory",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Резьбовые виброкомпенсаторы",
        link: "trubniy-prokat/rezbovye-vibrokompensatory",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Виброкомпенсаторы под приварку",
        link: "trubniy-prokat/vibrokompensatory-privarka",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Воздухоотводчики",
        link: "trubniy-prokat/vozduhootvodchiky",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Грязевик вертикальный",
        link: "trubniy-prokat/grazevik-vertikalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Грязевик горизонтальный",
        link: "trubniy-prokat/grazevik-gorizontalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки латунные",
        link: "trubniy-prokat/zadvishki-latunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки нержавеющие",
        link: "trubniy-prokat/zadvishki-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки стальные",
        link: "trubniy-prokat/zadvishki-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки чугунные",
        link: "trubniy-prokat/zadvishki-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы дисковые поворотные чугунные",
        link: "trubniy-prokat/zatvory-diskovie-povorotnye-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы дисковые поворотные нержавеющие",
        link: "trubniy-prokat/zatvory-diskovie-povorotnye-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы шиберные чугунные",
        link: "trubniy-prokat/zatvory-shibernye-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы шиберные нержавеющие",
        link: "trubniy-prokat/zatvory-shibernye-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные стальные",
        link: "trubniy-prokat/klapany-blanace-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные чугунные",
        link: "trubniy-prokat/klapany-blanace-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные латунные",
        link: "trubniy-prokat/klapany-blanace-latunye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные бронзовые",
        link: "trubniy-prokat/klapany-blanace-bronze",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны регулирующие 2-х ходовые",
        link: "trubniy-prokat/klapany-regul-dvuhodovye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны регулирующие 3-х ходовые",
        link: "trubniy-prokat/klapany-regul-trehodovye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Регуляторы перепада давления",
        link: "trubniy-prokat/regulatory-davlenya",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Элементы управления",
        link: "trubniy-prokat/elementy-upravlenya",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные нержавеющие",
        link: "trubniy-prokat/klapany-obrat-nershaveyshye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные латунные",
        link: "trubniy-prokat/klapany-obrat-latunnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные стальные",
        link: "trubniy-prokat/klapany-obrat-stalnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные бронзовые",
        link: "trubniy-prokat/klapany-obrat-bronze",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные чугунные",
        link: "trubniy-prokat/klapany-obrat-chugunnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные чугунные",
        link: "trubniy-prokat/klapany-predohran-chugunnye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные нержавеющие",
        link: "trubniy-prokat/klapany-predohran-nershaveyshye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные стальные",
        link: "trubniy-prokat/klapany-predohran-stalnye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Термостатический конденсатоотводчик",
        link: "trubniy-prokat/termostaticheskiy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Поплавковый конденсатоотводчик",
        link: "trubniy-prokat/poplavkoviy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Термодинамический конденсатоотводчик",
        link: "trubniy-prokat/termodinamicheskiy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны стальные",
        link: "trubniy-prokat/sharovye-krany-stalnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны чугунные",
        link: "trubniy-prokat/sharovye-krany-shugunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны нержавеющие",
        link: "trubniy-prokat/sharovye-krany-nershaveyshye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны хладостойкие",
        link: "trubniy-prokat/sharovye-krany-hladostoykye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны латунные",
        link: "trubniy-prokat/sharovye-krany-latunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Охладители проб",
        link: "trubniy-prokat/ohladitely-prob",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Приводы Электрические",
        link: "trubniy-prokat/provody-elektricheskie",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Приводы Пневматические",
        link: "trubniy-prokat/privody-pnevmaticheskye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Смотровые стекла",
        link: "trubniy-prokat/smotrovye-stekla",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры чугунные",
        link: "trubniy-prokat/filtry-chugunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры стальные",
        link: "trubniy-prokat/filtry-stalnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры нержавеющие",
        link: "trubniy-prokat/filtry-nershaveyshye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры латунные",
        link: "trubniy-prokat/filtry-latunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Электродные датчики",
        link: "trubniy-prokat/elektronye-datchiky",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Черные металлы",
    href: "cherniy-prokat",
    metaData: "Купить Чёрный металлопрокат оптом и в розницу",
    links: [
      {
        title: "Арматура / Катанка",
        link: "cherniy-prokat/armatura",
        img: "armaturaCatalog",
        metaData: "Прокат",
      },
      // {
      //   title: "Сетка",
      //   link: "cherniy-prokat/setka",
      //   img: "armaturaCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Балка",
        link: "cherniy-prokat/beam",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса г/к",
        link: "cherniy-prokat/polosa",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "cherniy-prokat/corner",
        img: "cornerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "cherniy-prokat/circle",
        img: "circleCatalog",
        metaData: "Прокат",
      },
      {
        title: "Швеллер",
        link: "cherniy-prokat/shveller",
        img: "shvellerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "cherniy-prokat/pipe",
        img: "pipeCatalog",
        metaData: "Прокат",
      },
      {
        title: "Цинк",
        link: "cherniy-prokat/zinc",
        img: "zincImg",
        metaData: "Цинковый Прокат купить",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Лист",
        link: "cherniy-prokat/list",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Судовая сталь",
        link: "cherniy-prokat/sudovaya_stal",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Поковки",
        link: "cherniy-prokat/pokovky",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Прецензионные сплавы",
    href: "precensplav-prokat",
    metaData: "Купить Прецензионные сплавы оптом и в розницу",
    links: [
      {
        title: "Нихром",
        link: "precensplav/nihrom",
        img: "nihromPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фехраль",
        link: "precensplav/fehral",
        img: "fehralPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Пермаллой",
        link: "precensplav/permalloy",
        img: "permalloyPrecenCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Нержавеющие металлы",
    href: "nershav-prokat",
    metaData: "Купить Нержавеющий металлопрокат оптом и в розницу",
    links: [
      {
        title: "Лист",
        link: "nershav-prokat/list-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "nershav-prokat/lenta-nershav",
        img: "lentaNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "nershav-prokat/truba-nershav",
        img: "pipeNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "nershav-prokat/corner-nershav",
        img: "cornerNershavCatalog",
        metaData: "Прокат",
      },
      // {
      //   title: "Квадрат",
      //   link: "nershav-prokat/square-nershav",
      //   img: "squareNershavCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Шестигранник",
        link: "nershav-prokat/hexagon-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "nershav-prokat/circle-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса",
        link: "nershav-prokat/polosa-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "nershav-prokat/grid-nershav",
        img: "gridNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Метизы и Грузовое оборудование",
    href: "metizi-prokat",
    metaData: "Купить Метизы оптом и в розницу",
    links: [
      {
        title: "Калибровка",
        link: "metizi-prokat/kalibrovka",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "lentaZincCatalog",
        metaData: "Прокат",
      },
      {
        title: "Проволока",
        link: "metizi-prokat/wire-metizi",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шпильки",
        link: "metizi-prokat/shpilki",
        img: "shpilkiCatalog",
        metaData: "Прокат",
      },
      {
        title: "Болты",
        link: "metizi-prokat/bolty",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Гайки",
        link: "metizi-prokat/gaiky",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Фундаментные болты",
        link: "metizi-prokat/fundament-bolty",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Канаты",
        link: "metizi-prokat/kanaty",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "metizi-prokat/setka",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Стропы. Канатные",
        link: "metizi-prokat/stropy-kanatnye",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Стропы. Текстильные",
        link: "metizi-prokat/stropy-tekstilnye",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Стропы. Комплектующие",
        link: "metizi-prokat/stropy-komplektuyushchie",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Резино-технические радиационностойкие изделия",
    href: "rezino-tech-prokat",
    metaData:
      "Купить Резино-технические радиационностойкие изделия оптом и в розницу",
    links: [
      {
        title: "Пластины",
        link: "rezino-tech-prokat/plastiny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кольца",
        link: "rezino-tech-prokat/kolca",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Манжеты",
        link: "rezino-tech-prokat/manshety",
        img: "lentaZincCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шнуры",
        link: "rezino-tech-prokat/shnury",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Трубки",
        link: "rezino-tech-prokat/truby",
        img: "shpilkiCatalog",
        metaData: "Прокат",
      },
      {
        title: "Крупногабаритное кольцо",
        link: "rezino-tech-prokat/krupnogabarity-kolco",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Мембраны и экраны",
        link: "rezino-tech-prokat/membrany-ekrany",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Резинометаллические РТИ",
        link: "rezino-tech-prokat/rezinometal-rti",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Кабельная продукция",
    href: "kabelnaya-produkcia",
    metaData: "Купить Кабельную продукцию оптом и в розницу",
    links: [
      {
        title: "Кабели гибкие и шнуры для горных работ",
        link: "kabelnaya-produkcia/kabely-gipkie-i-shnury-dlya-gorny-rabot",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели для нестационарной прокладки",
        link: "kabelnaya-produkcia/kabely-dlya-nestacionarny-prokladky",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели для систем связи, сигнализации и телекоммуникаций",
        link: "kabelnaya-produkcia/kabely-glya-sistem-svyazy-signalizacyy-i-telekomunikacyy",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели и провода высоковольтные",
        link: "kabelnaya-produkcia/kabely-i-provoda-visokovoltny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели и шнуры микрофонные",
        link: "kabelnaya-produkcia/kabely-i-shnury-microfonny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели контрольные с изоляцией из полимерной композиции",
        link: "kabelnaya-produkcia/kabely-kontrolny-s-isolaciey-polimerny-kompozicy",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели контрольные с ПВХ изоляцией",
        link: "kabelnaya-produkcia/kabely-kontrolny-s-pvh-izolacy",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели контрольные с полиэтиленовой изоляцией",
        link: "kabelnaya-produkcia/kabely-kontrolny-polietileny-izolacy",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели монтажные",
        link: "kabelnaya-produkcia/kabely-montashny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели промышленные интерфейсные",
        link: "kabelnaya-produkcia/kabely-promishleny-interface",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели противопожарной сигнализации",
        link: "kabelnaya-produkcia/kabely-protivoposharny-signaly",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели сигнально-блокировочные",
        link: "kabelnaya-produkcia/kabely-signaly-blokirovochny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели силовые с бумажно-пропитанной изоляцией",
        link: "kabelnaya-produkcia/kabely-silovie-bumashny-propitye-izolacy",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кабели силовые с изоляцией из полимерной композиции до 6 кВ",
        link: "kabelnaya-produkcia/kabely-silovie-izolacy-polymer-kompozicyy-6kv",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      // {
      //   title: "Кабели силовые с изоляцией из сшитого полиэтилена 6...35 кВ",
      //   link: "kabelnaya-produkcia/kabely-silovie-izolacy-shitok-politie-6-35kv",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели силовые с ПВХ изоляцией до 6 кВ",
      //   link: "kabelnaya-produkcia/kabely-siovy-pvh-izolacy-6kv",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели силовые с полиэтиленовой изоляцией до 6 кВ",
      //   link: "kabelnaya-produkcia/kabely-siovy-polietelen-izolacy-6kv",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели силовые с резиновой изоляцией",
      //   link: "kabelnaya-produkcia/kabely-silovy-rezinovy-izolacy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели судовые с резиновой изоляцией",
      //   link: "kabelnaya-produkcia/kabely-sudovy-rezinovy-izolacy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели телефонные",
      //   link: "kabelnaya-produkcia/kabely-telephony",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Кабели управления",
      //   link: "kabelnaya-produkcia/kabely-upravleny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода для бортовой сети",
      //   link: "kabelnaya-produkcia/provoda-dlya-bortovoy-sety",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода для взрывных работ и сапёрные",
      //   link: "kabelnaya-produkcia/provoda-dlya-vsrivny-rabot-saperny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода для водопогружных электродвигателей",
      //   link: "kabelnaya-produkcia/provoda-dlya-vodopogrushny-elektrodvygately",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода для радио- и электроустановок",
      //   link: "kabelnaya-produkcia/provoda-dlya-radio-elektroustanovky",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода и кабели нагревательные",
      //   link: "kabelnaya-produkcia/provoda-kabely-nagrevatelny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода и кабели связи полевые",
      //   link: "kabelnaya-produkcia/provoda-kabely-svyazy-polevy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title:
      //     "Провода и кабели термопарные, термоэлектродные и термокомпенсационные",
      //   link: "kabelnaya-produkcia/provoda-kabely-termozny-termoelektrodny-termokopensacy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода и шнуры для бытовых электроприборов",
      //   link: "kabelnaya-produkcia/provoda-shnury-bytavy-electropribory",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода монтажные",
      //   link: "kabelnaya-produkcia/provoda-monstashny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода монтажные с комбинированной изоляцией",
      //   link: "kabelnaya-produkcia/provoda-monstashny-kombynirovany-izolacy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода неизолированные",
      //   link: "kabelnaya-produkcia/provoda-neizolirovany",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода с асбестовой изоляцией",
      //   link: "kabelnaya-produkcia/provoda-asbestovy-izolacy",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода силовые автотракторные",
      //   link: "kabelnaya-produkcia/provoda-silovy-avtotraktorny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода силовые термостойкие",
      //   link: "kabelnaya-produkcia/provoda-silovy-termostoiky",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода телефонные, радиотрансляционные и распределительные",
      //   link: "kabelnaya-produkcia/provoda-telephony-radiotranslacy-raspredelitelny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Провода установочные",
      //   link: "kabelnaya-produkcia/provoda-ustanovochny",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
      // {
      //   title: "Самонесущие изолированные провода",
      //   link: "kabelnaya-produkcia/samosushny-izolirovany-provoda",
      //   img: "kalibrovkaCatalog",
      //   metaData: "Прокат",
      // },
    ],
  },
  {
    label: "Металлы и сплавы",
    href: "metally-i-splavy",
    metaData: "Купить Металлы и сплавы оптом и в розницу",
    links: [
      {
        title: "Индий",
        link: "metally-i-splavy/indiy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Германий",
        link: "metally-i-splavy/germaniy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Гафний",
        link: "metally-i-splavy/grafniy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Вольфрам",
        link: "metally-i-splavy/volfram",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Висмут",
        link: "metally-i-splavy/vismut",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Ванадий",
        link: "metally-i-splavy/vanady",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Баббит Б-83",
        link: "metally-i-splavy/babbyt-b-83",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Медно-фосфорные припои",
        link: "metally-i-splavy/medno-phosforny-pripoiy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Молибден",
        link: "metally-i-splavy/molibden",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Коксовая мелочь",
        link: "metally-i-splavy/koksovaiya-meloch",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Галий",
        link: "metally-i-splavy/galiy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Магний",
        link: "metally-i-splavy/magniy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Марганец металлический",
        link: "metally-i-splavy/marganec-metalichesky",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Баббит Б-16",
        link: "metally-i-splavy/babby-b-16",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Аноды серебряные",
        link: "metally-i-splavy/anody-serebryany",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Технический кремний",
        link: "metally-i-splavy/tehnichensky-kremniy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Припои на основе серебра",
        link: "metally-i-splavy/pripoiy-na-osnove_serbra",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Палладиевый припой",
        link: "metally-i-splavy/paladievy-pripoy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Дробь стальная техническая",
        link: "metally-i-splavy/drob-stalnaya-tehnicheskaya",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Иттрий",
        link: "metally-i-splavy/ittriy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Европий",
        link: "metally-i-splavy/evropiy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Кадмий",
        link: "metally-i-splavy/kadmiy",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Кокс литейный",
        link: "metally-i-splavy/koks-liteiny",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Кобальт",
        link: "metally-i-splavy/kobalt",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
      {
        title: "Кальциевые баббиты",
        link: "metally-i-splavy/kalcevidy-babbity",
        img: "kalibrovkaCatalog",
        metaData: "Купить",
      },
    ],
  },
];
