export const menuCatalog = [
  {
    label: "Цветные металлы",
    href: "tsvetnoi-prokat",
    metaData: "Купить Цветной металлопрокат оптом и в розницу",
    links: [
      {
        title: "Алюминий",
        link: "tsvetnoi-prokat/aluminum",
        img: "aluminumImg",
        metaData: "Алюминиевый Прокат купить",
      },
      {
        title: "Бронза",
        link: "tsvetnoi-prokat/bronze",
        img: "bronzeImg",
        metaData: "Бронзовый Прокат купить",
      },
      {
        title: "Дюраль",
        link: "tsvetnoi-prokat/dural",
        img: "duralImg",
        metaData: "Дюралевый Прокат купить",
      },
      {
        title: "Олово",
        link: "tsvetnoi-prokat/olovo",
        img: "olovoImg",
        metaData: "Оловянный Прокат купить",
      },
      {
        title: "Титан",
        link: "tsvetnoi-prokat/titan",
        img: "titanImg",
        metaData: "Титановый Прокат купить",
      },
      {
        title: "Медь",
        link: "tsvetnoi-prokat/copper",
        img: "copperImg",
        metaData: "Медный Прокат купить",
      },
      {
        title: "Латунь",
        link: "tsvetnoi-prokat/brass",
        img: "brassImg",
        metaData: "Латунный Прокат купить",
      },
      {
        title: "Свинец",
        link: "tsvetnoi-prokat/lead",
        img: "leadImg",
        metaData: "Свинцовый Прокат купить",
      },
    ],
  },
  {
    label: "Трубопроводная арматура",
    href: "trubniy-prokat",
    metaData: "Купить Трубопроводная арматура оптом и в розницу",
    links: [
      // {
      //   title: "Запорная Арматура",
      //   link: "trubniy-prokat/zapor",
      //   img: "zaporTrubCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Отопление",
        link: "trubniy-prokat/otoplenye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Водоснабжение",
        link: "trubniy-prokat/vodosnabshenye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "ГВС",
        link: "trubniy-prokat/gvs",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Вентили нержавеющие",
        link: "trubniy-prokat/venteli-nershav",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Вентили стальные",
        link: "trubniy-prokat/venteli-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Чугунные вентили",
        link: "trubniy-prokat/venteli-shugunye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фланцевые виброкомпенсаторы",
        link: "trubniy-prokat/flancevye-vibrokompensatory",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Резьбовые виброкомпенсаторы",
        link: "trubniy-prokat/rezbovye-vibrokompensatory",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Виброкомпенсаторы под приварку",
        link: "trubniy-prokat/vibrokompensatory-privarka",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Воздухоотводчики",
        link: "trubniy-prokat/vozduhootvodchiky",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Грязевик вертикальный",
        link: "trubniy-prokat/grazevik-vertikalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Грязевик горизонтальный",
        link: "trubniy-prokat/grazevik-gorizontalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Чугунные вентили",
        link: "trubniy-prokat/venteli-shugunye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки латунные",
        link: "trubniy-prokat/zadvishki-latunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки нержавеющие",
        link: "trubniy-prokat/zadvishki-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки стальные",
        link: "trubniy-prokat/zadvishki-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Задвижки чугунные",
        link: "trubniy-prokat/zadvishki-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы дисковые поворотные чугунные",
        link: "trubniy-prokat/zatvory-diskovie-povorotnye-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы дисковые поворотные нержавеющие",
        link: "trubniy-prokat/zatvory-diskovie-povorotnye-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы шиберные чугунные",
        link: "trubniy-prokat/zatvory-shibernye-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Затворы шиберные нержавеющие",
        link: "trubniy-prokat/zatvory-shibernye-nershaveyshye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные стальные",
        link: "trubniy-prokat/klapany-blanace-stalnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные чугунные",
        link: "trubniy-prokat/klapany-blanace-chugunnye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные латунные",
        link: "trubniy-prokat/klapany-blanace-latunye",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны балансировочные бронзовые",
        link: "trubniy-prokat/klapany-blanace-bronze",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны регулирующие 2-х ходовые",
        link: "trubniy-prokat/klapany-regul-dvuhodovye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны регулирующие 3-х ходовые",
        link: "trubniy-prokat/klapany-regul-trehodovye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Регуляторы перепада давления",
        link: "trubniy-prokat/regulatory-davlenya",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Элементы управления",
        link: "trubniy-prokat/elementy-upravlenya",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные нержавеющие",
        link: "trubniy-prokat/klapany-obrat-nershaveyshye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные латунные",
        link: "trubniy-prokat/klapany-obrat-latunnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные стальные",
        link: "trubniy-prokat/klapany-obrat-stalnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные бронзовые",
        link: "trubniy-prokat/klapany-obrat-bronze",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны обратные чугунные",
        link: "trubniy-prokat/klapany-obrat-chugunnye",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные чугунные",
        link: "trubniy-prokat/klapany-predohran-chugunnye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные нержавеющие",
        link: "trubniy-prokat/klapany-predohran-nershaveyshye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны предохранительные стальные",
        link: "trubniy-prokat/klapany-predohran-stalnye",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Термостатический конденсатоотводчик",
        link: "trubniy-prokat/termostaticheskiy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Поплавковый конденсатоотводчик",
        link: "trubniy-prokat/poplavkoviy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Термодинамический конденсатоотводчик",
        link: "trubniy-prokat/termodinamicheskiy-kondensatootvodchik",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны стальные",
        link: "trubniy-prokat/sharovye-krany-stalnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны чугунные",
        link: "trubniy-prokat/sharovye-krany-shugunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны нержавеющие",
        link: "trubniy-prokat/sharovye-krany-nershaveyshye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны хладостойкие",
        link: "trubniy-prokat/sharovye-krany-hladostoykye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шаровые краны латунные",
        link: "trubniy-prokat/sharovye-krany-latunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Охладители проб",
        link: "trubniy-prokat/ohladitely-prob",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Приводы Электрические",
        link: "trubniy-prokat/provody-elektricheskie",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Приводы Пневматические",
        link: "trubniy-prokat/privody-pnevmaticheskye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Смотровые стекла",
        link: "trubniy-prokat/smotrovye-stekla",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры чугунные",
        link: "trubniy-prokat/filtry-chugunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры стальные",
        link: "trubniy-prokat/filtry-stalnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры нержавеющие",
        link: "trubniy-prokat/filtry-nershaveyshye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фильтры латунные",
        link: "trubniy-prokat/filtry-latunnye",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
      {
        title: "Электродные датчики",
        link: "trubniy-prokat/elektronye-datchiky",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Черные металлы",
    href: "cherniy-prokat",
    metaData: "Купить Чёрный металлопрокат оптом и в розницу",
    links: [
      {
        title: "Арматура / Катанка",
        link: "cherniy-prokat/armatura",
        img: "armaturaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Балка",
        link: "cherniy-prokat/beam",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса г/к",
        link: "cherniy-prokat/polosa",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "cherniy-prokat/corner",
        img: "cornerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "cherniy-prokat/circle",
        img: "circleCatalog",
        metaData: "Прокат",
      },
      {
        title: "Швеллер",
        link: "cherniy-prokat/shveller",
        img: "shvellerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "cherniy-prokat/pipe",
        img: "pipeCatalog",
        metaData: "Прокат",
      },
      {
        title: "Цинк",
        link: "cherniy-prokat/zinc",
        img: "zincImg",
        metaData: "Цинковый Прокат купить",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Лист",
        link: "cherniy-prokat/list",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Судовая сталь",
        link: "cherniy-prokat/sudovaya_stal",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Поковки",
        link: "cherniy-prokat/pokovky",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Прецензионные сплавы",
    href: "precensplav-prokat",
    metaData: "Купить Прецензионные сплавы оптом и в розницу",
    links: [
      {
        title: "Нихром",
        link: "precensplav/nihrom",
        img: "nihromPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фехраль",
        link: "precensplav/fehral",
        img: "fehralPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Пермаллой",
        link: "precensplav/permalloy",
        img: "permalloyPrecenCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Нержавеющие металлы",
    href: "nershav-prokat",
    metaData: "Купить Нержавеющий металлопрокат оптом и в розницу",
    links: [
      {
        title: "Лист",
        link: "nershav-prokat/list-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "nershav-prokat/lenta-nershav",
        img: "lentaNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "nershav-prokat/truba-nershav",
        img: "pipeNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "nershav-prokat/corner-nershav",
        img: "cornerNershavCatalog",
        metaData: "Прокат",
      },
      // {
      //   title: "Квадрат",
      //   link: "nershav-prokat/square-nershav",
      //   img: "squareNershavCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Шестигранник",
        link: "nershav-prokat/hexagon-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "nershav-prokat/circle-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса",
        link: "nershav-prokat/polosa-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "nershav-prokat/grid-nershav",
        img: "gridNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Метизы",
    href: "metizi-prokat",
    metaData: "Купить Метизы оптом и в розницу",
    links: [
      {
        title: "Калибровка",
        link: "metizi-prokat/kalibrovka",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "lentaZincCatalog",
        metaData: "Прокат",
      },
      {
        title: "Проволока",
        link: "metizi-prokat/wire-metizi",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шпильки",
        link: "metizi-prokat/shpilki",
        img: "shpilkiCatalog",
        metaData: "Прокат",
      },
      {
        title: "Болты",
        link: "metizi-prokat/bolty",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Гайки",
        link: "metizi-prokat/gaiky",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Фундаментные болты",
        link: "metizi-prokat/fundament-bolty",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Резино-технические радиационностойкие изделия",
    href: "rezino-tech-prokat",
    metaData:
      "Купить Резино-технические радиационностойкие изделия оптом и в розницу",
    links: [
      {
        title: "Пластины",
        link: "rezino-tech-prokat/plastiny",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Кольца",
        link: "rezino-tech-prokat/kolca",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Манжеты",
        link: "rezino-tech-prokat/manshety",
        img: "lentaZincCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шнуры",
        link: "rezino-tech-prokat/shnury",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Трубки",
        link: "rezino-tech-prokat/truby",
        img: "shpilkiCatalog",
        metaData: "Прокат",
      },
      {
        title: "Крупногабаритное кольцо",
        link: "rezino-tech-prokat/krupnogabarity-kolco",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Мембраны и экраны",
        link: "rezino-tech-prokat/membrany-ekrany",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      {
        title: "Резинометаллические РТИ",
        link: "rezino-tech-prokat/rezinometal-rti",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
    ],
  },
];
