export const menuCatalog = [
  {
    label: "Цветные металлы",
    href: "tsvetnoi-prokat",
    metaData: "Купить Цветной металлопрокат оптом и в розницу",
    links: [
      {
        title: "Алюминий",
        link: "tsvetnoi-prokat/aluminum",
        img: "aluminumImg",
        metaData: "Алюминиевый Прокат купить",
      },
      {
        title: "Бронза",
        link: "tsvetnoi-prokat/bronze",
        img: "bronzeImg",
        metaData: "Бронзовый Прокат купить",
      },
      {
        title: "Дюраль",
        link: "tsvetnoi-prokat/durak",
        img: "duralImg",
        metaData: "Дюралевый Прокат купить",
      },
      {
        title: "Олово",
        link: "tsvetnoi-prokat/olovo",
        img: "olovoImg",
        metaData: "Оловянный Прокат купить",
      },
      {
        title: "Титан",
        link: "tsvetnoi-prokat/titan",
        img: "titanImg",
        metaData: "Титановый Прокат купить",
      },
      {
        title: "Медь",
        link: "tsvetnoi-prokat/copper",
        img: "copperImg",
        metaData: "Медный Прокат купить",
      },
      {
        title: "Латунь",
        link: "tsvetnoi-prokat/brass",
        img: "brassImg",
        metaData: "Латунный Прокат купить",
      },
      {
        title: "Свинец",
        link: "tsvetnoi-prokat/lead",
        img: "leadImg",
        metaData: "Свинцовый Прокат купить",
      },
      {
        title: "Цинк",
        link: "tsvetnoi-prokat/zinc",
        img: "zincImg",
        metaData: "Цинковый Прокат купить",
      },
    ],
  },
  {
    label: "Трубопроводная арматура",
    href: "trubniy-prokat",
    metaData: "Купить Трубопроводная арматура оптом и в розницу",
    links: [
      {
        title: "Запорная Арматура",
        link: "trubniy-prokat/aluminum",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Регулирующие ",
        link: "trubniy-prokat/bronze",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Обратные",
        link: "trubniy-prokat/durak",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Защиты",
        link: "trubniy-prokat/olovo",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Предохранительные",
        link: "trubniy-prokat/titan",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Продувки",
        link: "trubniy-prokat/copper",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Черные металлы",
    href: "cherniy-prokat",
    metaData: "Купить Чёрный металлопрокат оптом и в розницу",
    links: [
      {
        title: "Арматура",
        link: "cherniy-prokat/aluminum",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Балка",
        link: "cherniy-prokat/bronze",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Рулонная сталь",
        link: "cherniy-prokat/durak",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "cherniy-prokat/olovo",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "cherniy-prokat/titan",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Швеллер",
        link: "cherniy-prokat/copper",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "cherniy-prokat/brass",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Прецензионные сплавы",
    href: "precensplav-prokat",
    metaData: "Купить Прецензионные сплавы оптом и в розницу",
    links: [
      {
        title: "Нихром",
        link: "precensplav/aluminum",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фехраль",
        link: "precensplav/bronze",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Пермаллой",
        link: "precensplav/durak",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Нержавеющие металлы",
    href: "nershav-prokat",
    metaData: "Купить Нержавеющий металлопрокат оптом и в розницу",
    links: [
      {
        title: "Лист",
        link: "nershav-prokat/aluminum",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "nershav-prokat/bronze",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "nershav-prokat/durak",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "nershav-prokat/olovo",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Квадрат",
        link: "nershav-prokat/titan",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса",
        link: "nershav-prokat/copper",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "nershav-prokat/brass",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Метизы",
    href: "metizi-prokat",
    metaData: "Купить Метизы оптом и в розницу",
    links: [
      {
        title: "Калибровка",
        link: "metizi-prokat/aluminum",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "metizi-prokat/bronze",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шпильки",
        link: "metizi-prokat/durak",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Болты и гайки",
        link: "metizi-prokat/olovo",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "metizi-prokat/titan",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
];
